In [14]:
import pandas as pd
#Conjunto de datos de preguntas y respuestas

In [17]:
datos =pd.read_csv('chocolate.csv')

In [18]:
datos
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2224 entries, 0 to 2223
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Unnamed: 0                        2224 non-null   int64  
 1   ref                               2224 non-null   int64  
 2   company                           2224 non-null   object 
 3   company_location                  2224 non-null   object 
 4   review_date                       2224 non-null   int64  
 5   country_of_bean_origin            2224 non-null   object 
 6   specific_bean_origin_or_bar_name  2224 non-null   object 
 7   cocoa_percent                     2224 non-null   float64
 8   rating                            2224 non-null   float64
 9   counts_of_ingredients             2224 non-null   int64  
 10  beans                             2224 non-null   object 
 11  cocoa_butter                      2224 non-null   object 
 12  vanill

In [23]:
datos['company']=datos['company'].astype('category')
datos['company']=datos['company'].cat.codes

datos['company_location']=datos['company_location'].astype('category')
datos['company_location']=datos['company_location'].cat.codes

datos['beans']=datos['beans'].astype('category')
datos['beans']=datos['beans'].cat.codes

datos['cocoa_butter']=datos['cocoa_butter'].astype('category')
datos['cocoa_butter']=datos['cocoa_butter'].cat.codes

datos['specific_bean_origin_or_bar_name']=datos['specific_bean_origin_or_bar_name'].astype('category')
datos['specific_bean_origin_or_bar_name']=datos['specific_bean_origin_or_bar_name'].cat.codes

datos['country_of_bean_origin']=datos['country_of_bean_origin'].astype('category')
datos['country_of_bean_origin']=datos['country_of_bean_origin'].cat.codes

datos['vanilla']=datos['vanilla'].astype('category')
datos['vanilla']=datos['vanilla'].cat.codes

datos['lecithin']=datos['lecithin'].astype('category')
datos['lecithin']=datos['lecithin'].cat.codes

datos['salt']=datos['salt'].astype('category')
datos['salt']=datos['salt'].cat.codes

datos['sugar']=datos['sugar'].astype('category')
datos['sugar']=datos['sugar'].cat.codes

datos['sweetener_without_sugar']=datos['sweetener_without_sugar'].astype('category')
datos['sweetener_without_sugar']=datos['sweetener_without_sugar'].cat.codes

datos['first_taste']=datos['first_taste'].astype('category')
datos['first_taste']=datos['first_taste'].cat.codes

datos['second_taste']=datos['second_taste'].astype('category')
datos['second_taste']=datos['second_taste'].cat.codes

datos['third_taste']=datos['third_taste'].astype('category')
datos['third_taste']=datos['third_taste'].cat.codes

datos['fourth_taste']=datos['fourth_taste'].astype('category')
datos['fourth_taste']=datos['fourth_taste'].cat.codes

datos


Unnamed: 0   ref  company  company_location  review_date  \
0              0  2454        0                59         2019   
1              1  2458        0                59         2019   
2              2  2454        0                59         2019   
3              3   797        1                17         2012   
4              4   797        1                17         2012   
...          ...   ...      ...               ...          ...   
2219        2219  1205      496                 2         2014   
2220        2220  1996      496                 2         2017   
2221        2221  2170      496                 2         2018   
2222        2222  2170      496                 2         2018   
2223        2223  2036      496                 2         2018   

      country_of_bean_origin  specific_bean_origin_or_bar_name  cocoa_percent  \
0                         28                               137           76.0   
1                         12                              1392           76.0   
2                         52                               654           76.0   
3                         36                              1003           63.0   
4                          3                               173           70.0   
...                      ...                               ...            ...   
2219                       2                              1098           80.0   
2220                       8                                 5           75.0   
2221                       1                               822           72.0   
2222                       9                               876           70.0   
2223                       2                               429           75.0   

      rating  counts_of_ingredients  ...  lecithin  salt  sugar  \
0       3.75                      3  ...         1     0      1   
1       3.50                      3  ...         1     0      1   
2       3.25                      3  ...         1     0      1   
3       3.75                      4  ...         0     0      1   
4       3.50                      4  ...         0     0      1   
...      ...                    ...  ...       ...   ...    ...   
2219    2.75                      4  ...         1     1      0   
2220    3.75                      3  ...         1     0      1   
2221    3.50                      3  ...         1     0      1   
2222    3.25                      3  ...         1     0      1   
2223    3.00                      3  ...         1     0      1   

      sweetener_without_sugar  first_taste  second_taste  third_taste  \
0                           0           86            27          111   
1                           0           86           460          256   
2                           0          319           126           26   
3                           0          137           222          247   
4                           0          437           288           -1   
...                       ...          ...           ...          ...   
2219                        1          446            84          316   
2220                        0          397           214           -1   
2221                        0          265           357            0   
2222                        0          130           255          180   
2223                        0          130           121           63   

      fourth_taste  company_location       cocoa_butter   
0               -1              U.S.A  have_cocoa_butter  
1               -1              U.S.A  have_cocoa_butter  
2               -1              U.S.A  have_cocoa_butter  
3               -1             France  have_cocoa_butter  
4               -1             France  have_cocoa_butter  
...            ...                ...                ...  
2219            -1            Austria  have_cocoa_butter  
2220            -1            Austria  have_cocoa_butter  
2221            -1         

In [24]:
datos
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2224 entries, 0 to 2223
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype   
---  ------                            --------------  -----   
 0   Unnamed: 0                        2224 non-null   int64   
 1   ref                               2224 non-null   int64   
 2   company                           2224 non-null   int16   
 3   company_location                  2224 non-null   int8    
 4   review_date                       2224 non-null   int64   
 5   country_of_bean_origin            2224 non-null   int8    
 6   specific_bean_origin_or_bar_name  2224 non-null   int16   
 7   cocoa_percent                     2224 non-null   float64 
 8   rating                            2224 non-null   float64 
 9   counts_of_ingredients             2224 non-null   int64   
 10  beans                             2224 non-null   int8    
 11  cocoa_butter                      2224 non-null   int8  

In [27]:
from sklearn.preprocessing import LabelEncoder

from sklearn import preprocessing

X = datos.iloc[:, :5].values
y = datos.iloc[:, 2].astype('float')

m = y.size


In [28]:
print(X)
print(y)

[[   0 2454    0   59 2019]
 [   1 2458    0   59 2019]
 [   2 2454    0   59 2019]
 ...
 [2221 2170  496    2 2018]
 [2222 2170  496    2 2018]
 [2223 2036  496    2 2018]]
0         0.0
1         0.0
2         0.0
3         1.0
4         1.0
        ...  
2219    496.0
2220    496.0
2221    496.0
2222    496.0
2223    496.0
Name: company, Length: 2224, dtype: float64


In [ ]:
# valores de prueba para los parámetros theta
theta_t = np.array([-2, -1, 1, 2], dtype=float)

# valores de prueba para las entradas
X_t = np.concatenate([np.ones((5, 1)), np.arange(1, 16).reshape(5, 3, order='F')/10.0], axis=1)
print(X_t)
# valores de testeo para las etiquetas
y_t = np.array([1, 0, 1, 0, 1])

# valores de testeo para el parametro de regularizacion
lambda_t = 3